# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: mysql_schedule_db
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3310:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_schedule_db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-schedule
    depends_on:
      - db
    ports:
      - 8003:80

volumes:
  dbbase:
